### ISSUE TITLE
Design for mobile

### ISSUE THREAD

**Issue by jonathansick** [astropy/learn-astropy#19]
In #15 we got the basic site, but didn't do any explicit work with a responsive design for mobile viewports. In particular, the header component is broken on mobile. Let's fix that up.

**Comment by BhavyaT-135** [comment]
Hi, @jonathansick. I am a front-end developer. I have set up the project on my local machine. Is it okay if I contribute to this issue? I can work step-by-step on components to make the site more responsive. We can have discussions to recognize the features that need improvement. 😊

**Comment by jonathansick** [comment]
HI @BhavyaT-135, the Astropy Project welcomes PRs, for sure and we'd appreciate your contributions. For our responsive design, the main things that need improvements are adapting the header and the search UI for narrow viewports.

**Comment by BhavyaT-135** [comment]
Thank you for the quick response @jonathansick, I will start working on it right away!

**Comment by BhavyaT-135** [comment]
Hi, @jonathansick! I started out with some changes in the header section. I made the header section responsive around 600px of the screen width because, at 600 px, the last anchor tag became unresponsive. Plus, I added a little padding in the content of the page cover below 600px. Could you please take a look and tell me if it looks alright? 😊 

This was how the header section along with the page cover looked previously.

![image](https://user-images.githubusercontent.com/55613637/175792621-1fbf6978-1e5b-4f30-9768-3d0d77987bb2.png)

After the changes, it looks like this.

![image](https://user-images.githubusercontent.com/55613637/175792674-38a96988-1eb3-4322-94b3-fa1ea6227f8c.png)

**Comment by jonathansick** [comment]
Thanks for working on this! The padding is great!

Design wise, do you think it would be possible to left-align everything in the nav bar in the mobile breakpoint? Same vertical order: Logo, followed by page links, followed by the link to the Astropy project, but all left-aligned with the content below?

**Comment by BhavyaT-135** [comment]
@jonathansick Thanks for the review! 

I'll work on the alignment of the navbar components and open a PR with the required changes. 😊

**Comment by BhavyaT-135** [comment]
Hi, @jonathansick I worked on the header and page cover and this is how it looks with the content left-aligned. I left some padding for the anchor tags so that they don't align with the main logo.

![image](https://user-images.githubusercontent.com/55613637/177007417-860a5fc0-af5a-4753-8576-ccfef80e9f0f.png)

Another way I can do this is by aligning it with the logo. 

![image](https://user-images.githubusercontent.com/55613637/177007450-978a4fb5-b6d4-4c99-9bf4-38409a8c9d24.png)

Which one looks better? 😊

**Comment by BhavyaT-135** [comment]
@jonathansick I was considering hiding the navbar when the screen resolution reduces beyond 600px. The user could navigate using the search bar. What do you think? Should I submit a pull request for the above changes first? 😊

**Comment by BhavyaT-135** [comment]
Hi, @jonathansick for making the search section responsive, should I hide the hits list when the screen resolution reduces to below 600px? The search box and the refinement section would still remain intact. What are your views? 😊

**Comment by BhavyaT-135** [comment]
Hey, @jonathansick I implemented a few things to improve the current design to make it more responsive. Kindly review the PR and let me know if anything else needs to be done. 😊
